FROM maven:3.8.6-eclipse-temurin-11 AS builder
WORKDIR /app

COPY spring-backend/ .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:11-jre
WORKDIR /app

COPY --from=builder /app/target/*.jar /app/app.jar

RUN adduser --system --group appuser
USER appuser

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
